<a href="https://colab.research.google.com/github/Mo-Jawad/chai-aur-python/blob/main/practice_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Practices**

In [1]:
import numpy as np

## Practice-1: array creation

In [2]:
np.random.randint(1, 100, (3, 3))

array([[66, 90, 21],
       [ 7,  5, 27],
       [37, 98, 26]])

## Practice -2: Array Filtering

In [3]:
arr = np.array([5, 10, 15, 20, 25])

filtered_arr = arr[arr > 12]

print("filtered Array is", filtered_arr)

filtered Array is [15 20 25]


## Practice -3: Array Math operation

In [8]:
gen_Arr = np.random.randint(1, 50, (1,6))

## operation performs
mean_Arr = np.mean(gen_Arr)
max_arr = np.max(gen_Arr)
min_arr = np.min(gen_Arr)
std_arr = np.std(gen_Arr)


# print of these values
print("Generated Array", gen_Arr)
print("Mean of this Array", mean_Arr)
print("Max value of this Array", max_arr)
print("Min Value of this Array", min_arr)
print("standard deviation of this Array", std_arr)



Generated Array [[12 13 25 48 25 11]]
Mean of this Array 22.333333333333332
Max value of this Array 48
Min Value of this Array 11
standard deviation of this Array 12.879786057574439


## Practice-4: Matrics multiplication

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

## operation
AB_multiply = np.dot(A, B)

## print

print("A =", A)
print("\n B =", B)
print("\n A * B =", AB_multiply)

A = [[1 2]
 [3 4]]

 B = [[5 6]
 [7 8]]

 A * B = [[19 22]
 [43 50]]


## practice-5: reshaping

In [16]:
ran_Arr = np.random.randint(1, 50, (1, 9))

reshaped_Arr = ran_Arr.reshape(3, 3)

print("Generated Array -> ", ran_Arr)
print("\n Reshaped Array -> ", reshaped_Arr)

Generated Array ->  [[ 3 27 17 44 25 19 46  3 38]]

 Reshaped Array ->  [[ 3 27 17]
 [44 25 19]
 [46  3 38]]
